### ISSUE TITLE
Enable full screen mode from embedded visualisation

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#10]
As a courtesy, a button that allows full screen mode from any embedded visualisation.

**Comment by Conal-Tuohy** [comment]
See https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Using_full_screen_mode

**Comment by asaletourneau** [comment]
Sorry mate, under the hammer this morning so not much time to read all the Firefox info. Is fullscreen mode possible? Cheers, Asa

**Comment by Conal-Tuohy** [comment]
Yes it is. 

Sorry that was just a note to myself. Don't bother to read it.

**Comment by asaletourneau** [comment]
No worries, just added a comment to the Share issue to hopefully make 
everything is  Crystal clear though I forgot to say, "Wondering if it's 
possible to move the share icon up the screen a bit?" Worried that some 
people might miss it where it is at the moment? I understand that you 
probably did this to ensure the visualisation doesn't end up obscuring it?

Cheers

Asa Letourneau
Project Officer ,Communications and Online Transformation, Public Record 
Office Victoria
03 9348 5759 I  0423 482 127 I  fax 03 9348 5656
asa.letourneau@prov.vic.gov.au

Please note I work from home on Mondays


 
Sailing into Melbourne exhibition, Old Treasury Building | 
http://www.oldtreasurybuilding.org.au
walata tyamateetj exhibition, Victorian Archives Centre | 
http://prov.vic.gov.au/whats-on/exhibitions
Research the Collection | http://prov.vic.gov.au/research

You must not copy, disclose, distribute, store or otherwise use this 
material without permission. Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments. The State does not accept liability in connection with 
computer viruses, data corruption, delay, interruption, unauthorised 
access or use.

**Comment by Conal-Tuohy** [comment]
in Chrome, the vis goes full screen but it doesn't grow to fit the full screen - it remains the size it was in the original page. If the original page had it as 100% size, then it will expand, but if in pixels it will remain the same size.

**Comment by asaletourneau** [comment]
I'm so over Chrome so I'm not too concerned about this. And while the viz 
doesn't work at all in IE8 I'm not sure if that's a concern given how old 
it is? What are your thoughts?

BTW I'm booked in to demo the vis to my manager Friday afternoon. Do you 
think you'll be able to fix the node drag issue and get the highlighting 
done by then? I think the node drag is the priority of the two as it's 
hard ton see anything properly without this functionality.

Cheers

Asa Letourneau
Project Officer ,Communications and Online Transformation, Public Record 
Office Victoria
03 9348 5759 I  0423 482 127 I  fax 03 9348 5656
asa.letourneau@prov.vic.gov.au

Please note I work from home on Mondays


 
Sailing into Melbourne exhibition, Old Treasury Building | 
http://www.oldtreasurybuilding.org.au
walata tyamateetj exhibition, Victorian Archives Centre | 
http://prov.vic.gov.au/whats-on/exhibitions
Research the Collection | http://prov.vic.gov.au/research

You must not copy, disclose, distribute, store or otherwise use this 
material without permission. Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments. The State does not accept liability in connection with 
computer viruses, data corruption, delay, interruption, unauthorised 
access or use.

**Comment by asaletourneau** [comment]
nice one!

Asa Letourneau
Project Officer ,Communications and Online Transformation, Public Record 
Office Victoria
03 9348 5759 I  0423 482 127 I  fax 03 9348 5656
asa.letourneau@prov.vic.gov.au

Please note I work from home on Mondays


 
Sailing into Melbourne exhibition, Old Treasury Building | 
http://www.oldtreasurybuilding.org.au
walata tyamateetj exhibition, Victorian Archives Centre | 
http://prov.vic.gov.au/whats-on/exhibitions
Research the Collection | http://prov.vic.gov.au/research

You must not copy, disclose, distribute, store or otherwise use this 
material without permission. Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments. The State does not accept liability in connection with 
computer viruses, data corruption, delay, interruption, unauthorised 
access or use.
