### ISSUE TITLE
Addition of 'Hide Labels' button to toolbar

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#15]
This should be the last front end task to complete after the more important Issues #12, #13 & #14 are completed, as well as the deployment document task from the back end list. Perhaps this button could be part of the work for issue #13 given it is the actual Revise Toolbar work?
 The reason for the button is that it is very easy to inadvertently make labels appear than I expected which clutters the space very quickly so I think it's i,important for the user to always have a way to hide the labels if they make this mistake.

**Comment by Conal-Tuohy** [comment]
Added in revision 554363552f452a025480278d357cb97511eff080
