### ISSUE TITLE
Help Box not moving in Internet Explorer or Chrome

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#17]
Help box visible but not moving in IE 11 or Chrome Version 39.0.2171.99 m (64-bit)

Help box moving smoothly in Firefox 38.40 though holding scroll bar to move down page moves entire box instead.

**Comment by Conal-Tuohy** [comment]
drag fixed in Chrome, though the dialog box is not quite finished (needs cosmetic work and close button). 

@asaletourneau can you verify the drag works for you in all browsers now? I know the drag toolbar is tiny and partially obscured by the close button, but I'm working on that independently.
