### ISSUE TITLE
Help Box Embed problem

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#18]
1. empty help box in embed in Chrome and I.E (box appears but no help text within it).
2. No help box appearing at all in embed in Firefox.

Given the embed is one of the truly valuable features of the project we do need this to work.

Cheers. I'll call you tomorrow, hopefully before you hop on a plane to Sydney or after you get back.

**Comment by Conal-Tuohy** [comment]
Can you put your web page onto a web server so you can load it with an http: rather than a file: URL? I suspect that may be the issue here.

**Comment by Conal-Tuohy** [comment]
Problem was due to provisualizer.js loading "help.html" with a base URL equal to the current page, rather than to the provisualizer.js file. Fixed.
