### ISSUE TITLE
default PROVisualizer to fullscren nas before please

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#19]
Hi Conal, unless I'm missing something really obvious ( which is entirely possible), it looks like PROVisualizer doesn't default to full screen on startup like it used to with version 1. Can you ensure that it starts in fullscreen please?
Cheers

**Comment by Conal-Tuohy** [comment]
The black borders are just there temporarily for testing purposes. It's to test the correctness of calculations that involve coordinates in the coordinate space used within the vis itself (the space in which the dots and lines, and help dialog are positioned), and the coordinate space of the browser window.

**Comment by asaletourneau** [comment]
Thanks for the clarification. 

Cheers :)

Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov.au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.
