### ISSUE TITLE
Embed resize fields issue

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#21]
It is possible to resize the embed dimensions in Firefox but this is not working in either Chrome Version 39.0.2171.99 m (64-bit) nor IE 11 simply because trying to enter a value in the input boxes provided for either width or height triggers the browser to select the text in the entire embed box instead. Probably best to understand this by trying it out in these browsers.

**Comment by Conal-Tuohy** [comment]
thanks for the heads up that this fails in Chrome! I have got it working in Chrome now ... testing with IE is next.

**Comment by asaletourneau** [comment]
Great news, thanks. I'm now also sending you an email to turn off the label fade as I've had a long hard think about this and given we have the 'hide labels' button I think the label fade is obsolete and doesn't enhance the user experience. I think it will ultimately prove frustrating.

**Comment by Conal-Tuohy** [comment]
Actually, can you test the embed editor in IE? I am having some technical problems here with my server which is preventing me from testing on Windows.

**Comment by asaletourneau** [comment]
Problem still persists as you'll see from the attached screen shot. IE still selects the entire embed code so that the field value replaces it instead of remaining in the field input box.
![ie embed issue](https://cloud.githubusercontent.com/assets/1021209/13764418/386a2130-eaa3-11e5-8efa-ab6e92abfc72.jpg)

**Comment by Conal-Tuohy** [comment]
Did you refresh the browser?

**Comment by asaletourneau** [comment]
Okay WORKING IN ALL BROWSERS!!!!!!!

**Comment by asaletourneau** [comment]
Taking the liberty o f closing this issue!
