### ISSUE TITLE
fullscreen button not appear in IE 11 only

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#22]

**Comment by asaletourneau** [comment]
I flagged this very 'softly' in  Enable full screen mode from embedded visualisation #10  so apologies for not making this issue more obvious by creating it by itself :(

**Comment by asaletourneau** [comment]
And I even cleared the cache and refreshed to double check.

**Comment by asaletourneau** [comment]
just got back from lunch and the button still hsard to see in IE11 and clicking on it once takes you to fulklscreen but clicking on it again doesn't take you out of fullscreen as it does in both Firefox and Chrome. See screnshot from IE below
![fullscreen button issue](https://cloud.githubusercontent.com/assets/1021209/13766876/dbc95614-eab9-11e5-921e-bdde5456b6b5.jpg)

**Comment by Conal-Tuohy** [comment]
fixed in revision cf978690b8f4d528a65a3e48fe3002175eae3d94
