### ISSUE TITLE
Phase 3: Title Layout Enhancement

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#23]
Hmm... I don't think it would guarantee a lack of overlaps, though it would improve matters. Perhaps just add it as an issue ("enhancement" type) and come back to it after some more thought.

On 14 April 2016 at 15:00, <Asa.Letourneau@prov.vic.gov.au> wrote:

Hi mate, just realised that this guy who is a professional search agent does make a good point when he says: 
" Agency (i.e. node) names overlap when multiple names (nodes) are showing. All text is running to the right of the screen, could a fix be made to the names top the left of screen align differently?" 

I think he means than for any node to the left of the visualisation 'half line', the end of the node title is positioned next to the node and for any node to theright of the visualisation 'half line', the start of the node title is positioned next to the node as we already have. This would mean that no titles should ever collide. I noticed that Google get around this by simply positioning node titles directly beneath the node and centred. Here's a screen shot of that using an early prototype of mine: 
![chief sec s](https://cloud.githubusercontent.com/assets/1021209/14518876/67a33e50-025e-11e6-9c49-4e3487885843.jpg)

**Comment by asaletourneau** [comment]
Despite creating this issue before any other it ranks lowest in priority and can be tackled after all of the other Phase 3 UI issues have been resolved.

**Comment by Conal-Tuohy** [comment]
I had a quick look and it looked so easy I just did it: e07ea66cd80675e25f20494e482ad75ebe57cd8e

**Comment by asaletourneau** [comment]
Thanks!!!!!!!!!!!!!!!!!!!! I think this really helps. What do you think? And in time for my Friday presentation. Brilliant :)

**Comment by Conal-Tuohy** [comment]
I think it does help, yes. Another thought I had was that we could alter the angle of the textual labels so that labels in the top right and bottom left quadrants, for instance, are angled slightly upward, and the top left and bottom right quadrants have labels that slope down and to the right.

**Comment by asaletourneau** [comment]
Hi,

I think we see what comes out of the user testing before we make any more 
tweaks as I think this is an adequate solution for now. On another 
note(and I may have mentioned this in an email but not as an issue in the 
repository) but the search functionality is still not working in the 
embed. Any ideas why?

Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov.au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.

**Comment by Conal-Tuohy** [comment]
Search works fine for me. Can you provide a link or some other documentation as to what's not working? And please, not on this issue, which is about a different matter.

**Comment by asaletourneau** [comment]
Okay and yes will create a separate issue. Off to lunch after sweating 
over a site map in ZVisio (very boring but necessary for migration. We're 
creating about 200 topicpages and 200 + Series pages when I'm wondering 
why we donb't just use the visualisation tool that's going to be embedded? 
Perhaps users will just use the visualization tool anyway!

Cheers

Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov.au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.
