### ISSUE TITLE
Phase 3: Modify Javascript to provide feedback for unsuccessful searches

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#26]

**Comment by Conal-Tuohy** [comment]
@asaletourneau do you have some preferred text to display?

**Comment by Conal-Tuohy** [comment]
Here's what I currently have:

![no-matches](https://cloud.githubusercontent.com/assets/1264711/14879742/654959ee-0d6e-11e6-851b-86c54ef215e3.png)

**Comment by Conal-Tuohy** [comment]
closing this now ... please reopen it if changes are needed

**Comment by asaletourneau** [comment]
Bugger, looks like my comment didn't save after re-opening the issue! I think we need a slightly friendlier message along the lines of "**No matches found** Your search turned up no results, please try again with a broader search."
