### ISSUE TITLE
Highlight connected lines when a node is selected

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/Provisualizer#3]
This helps to visualize the set of neighbours of a specific node.

**Comment by asaletourneau** [comment]
Thought this image might clarify the 'look' I'm after (don't necessarilly need the directions, just the highlighted edges...
![highlight](https://cloud.githubusercontent.com/assets/1021209/6589852/65b82554-c7fb-11e4-9634-5063d4d3eed1.JPG)

**Comment by asaletourneau** [comment]
When you click on the node, in this case I clicked on the Chief Secretary's Department showing connections to all the Series. Note thgis is a screenbshot from my Google Fusion prototype from November 2014
Cheers

**Comment by Conal-Tuohy** [comment]
implemented in commit 6416f40
