### ISSUE TITLE
change landing page to http://prov-data.conaltuohy.com/Provisualizer/#soil

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#31]
I recently realized that the current landing page http://prov-data.conaltuohy.com/Provisualizer/#Aboriginal_1840
 with a date  poses a problem for users who might forget to delete the date when executing subsequent searches.I think we need to use this new landing page http://prov-data.conaltuohy.com/Provisualizer/#soil   thatsolves this problem with the added benefit of illustrating very clearly the Function/Agency/Series relationship.

**Comment by Conal-Tuohy** [comment]
done in revision 220573e2b888f11209f4b09208877e0257565f86
