### ISSUE TITLE
Embed code not working in Firefox and Chrome

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#32]
I copied the embed text after changing the width and height then saved it as a text file then renamed the extension html so I could open it in a browser (attached). It opened up in all browsers but the Function drop down list and search only works in Internet Explorer not Chrome or Firefox.
[Embed test 20160504.txt](https://github.com/Conal-Tuohy/Provisualizer/files/248124/Embed.test.20160504.txt)

**Comment by Conal-Tuohy** [comment]
I don't think this is a realistic scenario to be honest. I believe (thought I haven't checked) that the issue is because the embedding html is loaded in a browser from a local file rather than via http (which is what the embedding features is designed and tested for). 

The page at http://prov-data.conaltuohy.com/ for instance works fine.

**Comment by asaletourneau** [comment]
Okay I'm deferring to your obvious experience in these matters. Still 
confused why a local file loaded into IE works but not the other browsers?

Cheers

Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656
asa.letourneau@prov.vic.gov.au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.

**Comment by Conal-Tuohy** [comment]
Fixed misconfiguration of CORS on prov-data.conaltuohy.com

**Comment by asaletourneau** [comment]
genius
