### ISSUE TITLE
one apostrophe i Help text not displaying correctly

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#35]
Bug appearing in all browsers:
![apostrophe](https://cloud.githubusercontent.com/assets/1021209/15636977/f7b39a1e-2651-11e6-9dfb-d097aa77f7e9.jpg)

**Comment by Conal-Tuohy** [comment]
Needs explicit character set in the help.html

**Comment by Conal-Tuohy** [comment]
added character encoding declaration in c7126a4c6fedebd80c05773169a6765bcb5343ba

Live at http://prov-data.conaltuohy.com/Provisualizer/help.html

@asaletourneau could you check the revised help.html in IE or Edge or whatever browser that is please, and close the issue if you're happy?

Incidentally, I believe that your Microsoft browser was totally in the right and simply following the standard when it assumed that the page was encoded in ISO-8859-1. The other browsers I've used instead guessed UTF-8 as the encoding (a correct guess, but guessing is a divergence from the standard behaviour set out in the HTTP specification).
