### ISSUE TITLE
share and fullscreen buttons disappearing after return from fulldcreen to embed

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#37]
![share fullscreen bug](https://cloud.githubusercontent.com/assets/1021209/15637044/90e72b6e-2653-11e6-9a09-bce6cb85d274.jpg)

**Comment by Conal-Tuohy** [comment]
I can't access this site, it requires authentication

**Comment by asaletourneau** [comment]
Guessing you didn't receive my email from yesterday giving you login deets? username: wpguest password:wpguest.

**Comment by Conal-Tuohy** [comment]
Hmmm this is working OK for me in Firefox. 

In Chrome what happens is, the provisualizer started off small (i.e. boxed into a small region of the page), then happily went full screen, but coming back from full screen left it much larger and wider than it had originally been.

What browser is that in the screenshot? Is that Edge?

Now I think the embedding page itself is broken; could you check it @asaletourneau

**Comment by asaletourneau** [comment]
No issue in Firefox or Chrome (Version 39.0.2171.99 m (64-bit) so I'm closing this issue
