### ISSUE TITLE
Phase 4: Add a colour-coded key to the left of the visualization

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#38]
Add a colour-coded key to the left of the visualization, to describe the concepts of functions, agency, series, and associate them with the blue, yellow, and red circles in the visualization.

**Comment by asaletourneau** [comment]
As discussed I think we try this and then make a judgement call re its efficacy after seeing how much room it takes up in the embed. If it takes up too much room in the embed it might be a question of turning it on just for the fullscreen.

**Comment by Conal-Tuohy** [comment]
added in 674ad9cf3f7ad60541422f37af235a00df19e317
