### ISSUE TITLE
Phase 4: Modify the search user interface to add a "contains all words or numbers" option as a checkbox.

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#39]
Modify the search user interface to add a "contains all words or numbers" option as a checkbox.

**Comment by Conal-Tuohy** [comment]
done except the state of the option needs to be persisted in the URI fragment identifier along with the free text search and date

**Comment by asaletourneau** [comment]
Closing this because I'm pretty sure that fragment is now created?

**Comment by Conal-Tuohy** [comment]
No I haven't yet. Certainly if you share a search, you will want to be sure that the currently selected search algorithm is shared along with it.

**Comment by Conal-Tuohy** [comment]
@asaletourneau I did want to ask about the idea of dropping the old search algorithm completely; i.e. search is always for "all words", not for "exact phrase". I'm not sure there's much value in the (simpler) "exact phrase" algorithm, and there's always value in pruning excessive affordances - you can't have too much minimalism as I always say.

**Comment by asaletourneau** [comment]
I totally agree to make the "all words and numbers" search the default search and therefore delete the text and check box which will have the added benefit of fixing the zoom to fit issue it has created.

**Comment by Conal-Tuohy** [comment]
Reopening this. The checkbox should say "Exact words" and have the effect of making the user's input match only on whole words. e.g. search for "893" will not find "8935" and "bank" will not find "banking".

**Comment by Conal-Tuohy** [comment]
In revision feb17517463719d414bc91b035b4b40c7581ea02 added "Whole words" checkbox; when checked, the keywords specified must match entire words. 

The option is now persisted in the URI fragment so the state of the checkbox is not lost when a query is shared.
