### ISSUE TITLE
Phase 4: Modify visualization so that it automatically picks a zoom level adequate to the display all search results in the visualization panel.

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#41]
Modify visualization so that it automatically picks a zoom level adequate to the display all search results in the visualization panel.

**Comment by Conal-Tuohy** [comment]
done

**Comment by asaletourneau** [comment]
After the initial euphoria of seeing this and both the enhanced search, I've been trying to break it and noticed wuith the below screenshots of the embeded view, the zoom to fit still has the viz hiden behind the embed yellow labels:
![zoom bug1](https://cloud.githubusercontent.com/assets/1021209/15881118/da6408c8-2d76-11e6-93c5-4dab4ed9920a.jpg)
![oombug2](https://cloud.githubusercontent.com/assets/1021209/15881122/e1828e0e-2d76-11e6-8cdb-46d8e08d6f3b.jpg)
I've opened this issue but I do want to stress that if this is a simple fix pls proceed but if it's a bug that might jepordise your work thus far pls proceed with caution!

**Comment by asaletourneau** [comment]
Okay, displays fine in fullscreen so from a risk management perspective I'm saying that's good enough and re-closing this issue as I think we've come too far to fix the Drupal CSS overide issue that might jeopardize everything!
