### ISSUE TITLE
Share Your Search dialogue box

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#42]
Any chance of resizing the Share Your Search dialog box to reflect the style and functionality of the Help jquery dialogue box? Aditionally I noticed that the words Need Help? are sitting askew so they need to be realigned please to fit inside the Help dialogue box  toolbar please.
![share this and help dialogue box issues](https://cloud.githubusercontent.com/assets/1021209/15884046/dd502214-2d90-11e6-9765-3cc76c874311.jpg)

**Comment by Conal-Tuohy** [comment]
Finally looking at this ticket ... is the "needs help" part of the problem still there for you, @asaletourneau ? The "needs help" looks fine for me - I wonder if I've fixed this already, or if this was a symptom of your very old Firefox version?

**Comment by asaletourneau** [comment]
Hi buddy, Assuming you atre in NZ now and that we'll talk properly on your return. The Need elp? text sits nice in the veryical centre of the toolbar in Firefox, Chrome and I.E. The only bigger issues are 1. the Share box needs to follow the style of the Help box and 2. we definitelyt need the 'exact phrase' search option to get arround false results for VA 475 or VPRS 1189 etc Hope you are holding up okay? We won't bother installing to our server until we speak and resolve all remaining issues.

**Comment by asaletourneau** [comment]
Hi buddy, Hope you are all holding up okay at what must be an incredibly 
difficulkt time. I've added my response on Github if you'd like to look at 
that.

Healing thoughts coming your way!
:)

Asa Letourneau
Online Engagement Officer
T:  03 9348 5759  F:  03 9348 5656 M: 0423482127
asa.letourneau@prov.vic.gov.au

Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051
www.prov.vic.gov.au
 (Please Note that I work from home on Mondays with no remote access.)

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Our offices are located on the land of the Kulin Nations. We acknowledge 
and pay our respects to the Traditional Owners, past and present. 

You must not copy, disclose, distribute, store or otherwise use this 
material without permission . Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments . The State does not accept liability in connection with 
computer viruses , data corruption, delay, interruption, unauthorised 
access or use.

**Comment by Conal-Tuohy** [comment]
Fixed height of sharing dialog in revision f8616473d00c7d6e6401aa2726ecd31199caac01

**Comment by Conal-Tuohy** [comment]
OK I believe this is all fixed.
