### ISSUE TITLE
key box overlapping search button

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#44]
Not sure why I didn't notice this before but in both IE and Chrome the Key box appears to be obscuring the Search button:
![image](https://cloud.githubusercontent.com/assets/1021209/16476741/9a9b4e1e-3ecd-11e6-9d20-065b86989b31.png)

**Comment by asaletourneau** [comment]
The good news is that the issue doesn't seem to appear in Firefox:
![overlap firefox 20160701](https://cloud.githubusercontent.com/assets/1021209/16507791/0b85dea8-3f70-11e6-9306-7dc78d6f3073.jpg)

**Comment by Conal-Tuohy** [comment]
Moved key box down in revision d363b28cef8e947ea6ed0a6a99d98501721df9b2
