### ISSUE TITLE
Sharing tools

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/Provisualizer#5]
Buttons for sharing on social media and for embedding.

**Comment by Conal-Tuohy** [comment]
e.g. https://public-record-office-victoria.culturalspot.org/exhibit/xQIyFBWD4rLiIA?position=0%3A0

**Comment by Conal-Tuohy** [comment]
013e9a9 implements Twitter and Facebook sharing

**Comment by asaletourneau** [comment]
Wondering if it's possible to add email to the share options as seen in the original url I cited above https://public-record-office-victoria.culturalspot.org/exhibit/xQIyFBWD4rLiIA?position=0%3A0 and obviously the embed option when you get onto that. And the way I'd love it to be offered to the user is like this so they can just copy and pastet the highlighted embed code. A no brainer and really helpful:
![embed](https://cloud.githubusercontent.com/assets/1021209/6679674/8b26c18a-cc9f-11e4-955e-79cb7f724223.JPG)
