### ISSUE TITLE
Enable embedding without use of an iframe

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#6]
Need to give users the option to leave the iframe embedded visualisation at any point and enter full screen mode so as to be able to bookmar and or share search results. It woiuld be ideal to prompt them with the following onscreen warning: "T bookmark or share your search result please enter full screen mode"

**Comment by Conal-Tuohy** [comment]
It is simpler to just not use an iframe; then there would be no need for this. The embedding functionality can be achieved just as easily without an iframe.

**Comment by asaletourneau** [comment]
Hi, That sounds fine as long as it works as easily as the iframe and we 
can still give people the code they'll need to embed the viz into their 
own site. Are you able to show me a working example to help me make a 
decision?

Cheers

Asa Letourneau
Project Officer ,Communications and Online Transformation, Public Record 
Office Victoria
03 9348 5759 I  0423 482 127 I  fax 03 9348 5656
asa.letourneau@prov.vic.gov.au

Please note I work from home on Mondays


 
Sailing into Melbourne exhibition, Old Treasury Building | 
http://www.oldtreasurybuilding.org.au
walata tyamateetj exhibition, Victorian Archives Centre | 
http://prov.vic.gov.au/whats-on/exhibitions
Research the Collection | http://prov.vic.gov.au/research

You must not copy, disclose, distribute, store or otherwise use this 
material without permission. Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments. The State does not accept liability in connection with 
computer viruses, data corruption, delay, interruption, unauthorised 
access or use.

**Comment by Conal-Tuohy** [comment]
http://conaltuohy.com/clients/prov/provisualizer/embedding/#liquor

**Comment by Conal-Tuohy** [comment]
```html
<div id="provisualizer" style="width: 800px; height:500px; border: 1px solid black;">
	<script src="http://d3js.org/d3.v3.min.js"></script>
	<script id="provisualizer-script" 
		src="http://conaltuohy.com/clients/prov/provisualizer/provisualizer.js"></script>
</div>
```

**Comment by asaletourneau** [comment]
freakin brilliant! All we'll need to do is allow the user to click on the embed icon from the Share tab that will bring up the embed code in a box that will prompt them to "Copy and Paste embed code into your own website."
