### ISSUE TITLE
Initial loading of data is slow

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/Provisualizer#8]
Compress the data? Eliminate duplicate rows in the data files? Add some kind of "loading" spinning icon to mesmerise users while they wait?

**Comment by asaletourneau** [comment]
loading icon might work though i don't actually think it takes long at all so it might damage us to draw their attention to it. I suggest doing this if we get complaints from the focus group

**Comment by asaletourneau** [comment]
As far as I can see it loads really fast so I reckon this issue is irrelevant 😀
